/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly;

/**
 *
 * @author ADMIN
 */
public class JfrTest extends javax.swing.JFrame {

    Thread t;
    Thread t2;
    Thread t3;

    /**
     * Creates new form JfrTest
     */
    public JfrTest() {
        initComponents();
        setLocationRelativeTo(null);
        phaiQuaTrai();
        traiQuaPhai();
        ten();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTrai = new javax.swing.JLabel();
        lbPhai = new javax.swing.JLabel();
        lbChay = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTrai.setText("Trai Qua Phai");

        lbPhai.setText("Phai Qua Trai");

        lbChay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbChay.setText("_______________");

        lbTen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTen.setText("âsasasasasasas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTrai)
                    .addComponent(lbPhai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbChay)
                    .addComponent(lbTen))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbTrai)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbChay)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPhai)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbTen)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbChay;
    private javax.swing.JLabel lbPhai;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbTrai;
    // End of variables declaration//GEN-END:variables
    public void phaiQuaTrai() {
        t = new Thread() {
            @Override
            public void run() {
                String line = lbPhai.getText() + "-";
                while (true) {
                    line = line.substring(1, line.length()) + line.charAt(0);
                    lbPhai.setText(line);
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                    }
                }

            }

        };
        t.start();
    }

    private void traiQuaPhai() {
        t2 = new Thread() {
            @Override
            public void run() {
                String line = lbTrai.getText() + " -";
                while (true) {
                    line = line.charAt(line.length() - 1) + line.substring(0, line.length() - 1);
                    lbTrai.setText(line);
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                    }
                }

            }

        };
        t2.start();
    }

    private void ten() {
        t3 = new Thread() {
            @Override
            public void run() {
                char kyTu, kyTu2;
                String line = lbTen.getText();
                String line2 = lbChay.getText();
                for (int i = 0; i < line.length(); i++) {

                        kyTu =line.charAt(i); //Cắt chuỗi
                        kyTu2 = line2.charAt(i);

                        String r = line.replace(kyTu, kyTu2);//Đổi vị trí
                        String r2 = line2.replace(kyTu2, kyTu);

                        lbChay.setText(r2 + "");
                        lbTen.setText(r + "");
                        
                    try {
                        Thread.sleep(1500);
                    } catch (Exception e) {
                    }
                }
            }

        };
        t3.start();
    }
}
