/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slide3;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author ADMIN
 */
public class Bai7_JSlider extends javax.swing.JFrame {

    /**
     * Creates new form Bai7_JSlider
     */
    public Bai7_JSlider() {
        initComponents();
        setLocationRelativeTo(null);
        Hashtable data = new Hashtable();
        String sMonths[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        for (int i = 0; i < 12; i++) {
            data.put(i, new JLabel(sMonths[i]));
        }
        sldMonth.setLabelTable(data);
        change();

        Calendar can = Calendar.getInstance();
    }

    public void change() {
        SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd - MMM - yyyy");
        int dd = sldDay.getValue();
        int mm = sldMonth.getValue();
        int yyyy = sldYear.getValue() - 1900;
        Date d = new Date(yyyy, mm, dd);
        txtDate.setText(sdf.format(d));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        sldDay = new javax.swing.JSlider();
        sldYear = new javax.swing.JSlider();
        sldMonth = new javax.swing.JSlider();
        txtDate = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sldDay.setMajorTickSpacing(7);
        sldDay.setMaximum(31);
        sldDay.setMinimum(1);
        sldDay.setMinorTickSpacing(1);
        sldDay.setPaintLabels(true);
        sldDay.setPaintTicks(true);
        sldDay.setValue(17);
        sldDay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDayStateChanged(evt);
            }
        });

        sldYear.setMajorTickSpacing(5);
        sldYear.setMaximum(2021);
        sldYear.setMinimum(2010);
        sldYear.setMinorTickSpacing(1);
        sldYear.setPaintLabels(true);
        sldYear.setPaintTicks(true);
        sldYear.setSnapToTicks(true);
        sldYear.setValue(2021);
        sldYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldYearStateChanged(evt);
            }
        });

        sldMonth.setMajorTickSpacing(1);
        sldMonth.setMaximum(11);
        sldMonth.setMinorTickSpacing(1);
        sldMonth.setPaintLabels(true);
        sldMonth.setPaintTicks(true);
        sldMonth.setToolTipText("");
        sldMonth.setValue(7);
        sldMonth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldMonthStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldDay, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(sldYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sldDay, sldMonth, sldYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(sldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {sldDay, sldMonth, sldYear});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDayStateChanged
        if (sldDay.getValueIsAdjusting()) //neu Slide chưa dừng thì không làm gì cả
        {
            return;
        }
        change();
    }//GEN-LAST:event_sldDayStateChanged

    private void sldMonthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldMonthStateChanged
        if (sldMonth.getValueIsAdjusting()) //neu Slide chưa dừng thì không làm gì cả
        {
            return;
        }
        change();
    }//GEN-LAST:event_sldMonthStateChanged

    private void sldYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldYearStateChanged
        if (sldYear.getValueIsAdjusting()) //neu Slide chưa dừng thì không làm gì cả
        {
            return;
        }
        change();
    }//GEN-LAST:event_sldYearStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai7_JSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai7_JSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai7_JSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai7_JSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai7_JSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSlider sldDay;
    private javax.swing.JSlider sldMonth;
    private javax.swing.JSlider sldYear;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables

}
