/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class JfrHoSoCaNhan extends javax.swing.JFrame {

    ArrayList<ThongTin> listTt = new ArrayList<>();
    int vitri;

    /**
     * Creates new form JfrHoSoCaNhan
     */
    public JfrHoSoCaNhan() {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        rdoNam.setSelected(rootPaneCheckingEnabled);
        data();
        fillToTable();
        vitri = 0;
        showDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        cbbNganhHoc = new javax.swing.JComboBox<>();
        txtKyNang = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnSapXepTheoTen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowData = new javax.swing.JTable();
        btnDau = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        lbHIenTai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hồ Sơ Cá Nhân");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Hồ Sơ Cá Nhân");

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Ngành học:");

        jLabel5.setText("Kỹ năng:");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        cbbNganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "TKDH", "Maketing", "Du Lịch", "Khách sạn" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnMoFile.setText("Open File");
        btnMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoFileActionPerformed(evt);
            }
        });

        btnLuuFile.setText("Save File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnSapXepTheoTen.setText("SX Theo tên");
        btnSapXepTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoTenActionPerformed(evt);
            }
        });

        tableShowData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Giới tính", "Ngành học", "Kỹ năng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableShowDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableShowData);

        btnDau.setText("|<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnCuoi.setText(">|");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdoNam))
                                        .addGap(31, 31, 31)
                                        .addComponent(rdoNu))
                                    .addComponent(txtKyNang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnXoa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLamMoi)
                                            .addComponent(btnCapNhat)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnMoFile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLuuFile))
                                    .addComponent(btnSapXepTheoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnDau)
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(lbHIenTai)
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(btnCuoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHoTen, txtKyNang});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnLamMoi, btnLuuFile, btnMoFile, btnThem, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLamMoi)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnCapNhat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtKyNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoFile)
                            .addComponent(btnLuuFile))
                        .addGap(18, 18, 18)
                        .addComponent(btnSapXepTheoTen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDau)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnCuoi)
                    .addComponent(lbHIenTai))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtHoTen, txtKyNang});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhat, btnLamMoi, btnLuuFile, btnMoFile, btnSapXepTheoTen, btnThem, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        add();
        fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
        fillToTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        update();
        fillToTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnSapXepTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoTenActionPerformed
        sortByName();
        fillToTable();
    }//GEN-LAST:event_btnSapXepTheoTenActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("test.txt"));
            oos.writeObject(listTt);
            oos.close();
            JOptionPane.showMessageDialog(this, "Lưu thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu file" + e);
        }
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoFileActionPerformed
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("test.txt"));
            listTt = (ArrayList<ThongTin>) ois.readObject();
            ois.close();
            fillToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi mở đọc file " + e);
        }
    }//GEN-LAST:event_btnMoFileActionPerformed

    private void tableShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableShowDataMouseClicked
        vitri = tableShowData.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tableShowDataMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (vitri < listTt.size() - 1) {
                vitri++;
            } else {
                vitri = 0;
            }
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        try {
            vitri = 0;
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        try {
            vitri = listTt.size() - 1;
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void data() {
        listTt.add(new ThongTin("Phương", "Nam", "CNTT", "Code"));
        listTt.add(new ThongTin("Phương2", "Nữ", "Du Lịch", "Nghỉ"));
        listTt.add(new ThongTin("Phương3", "Nam", "Khách sạn", "Ngủ"));
    }

    //Thêm thông tin
    public void add() {
        ThongTin tt = new ThongTin();
        try {
            if (checkTrung(txtHoTen.getText()) == true) {
                JOptionPane.showMessageDialog(this, "Trùng tên rồi !");
                return;
            }
        } catch (Exception e) {
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YY");
            sdf.setLenient(false);

            if (txtHoTen.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Rỗng ");
                return;
            } else {
                sdf.parse(txtHoTen.getText());
                tt.setHoTen(txtHoTen.getText().trim());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ngày tháng");
            return;
        }

        try {
            if (txtKyNang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống kỹ năng !");
                return;
            } else {
                tt.setKyNang(txtKyNang.getText().trim());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
        tt.setGioiTinh(gioiTinh());
        tt.setNganhHoc(cbbNganhHoc.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        listTt.add(tt);
    }

    public void check() {

    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tableShowData.getModel();
        model.setRowCount(0);
        for (ThongTin x : listTt) {
            model.addRow(new Object[]{
                x.getHoTen(), x.getGioiTinh(), x.getNganhHoc(), x.getKyNang()
            });
        }
    }

    public void delete() {
        int index = tableShowData.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Xác nhận", "Bạn có muốn xóa không ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choice == JOptionPane.YES_OPTION) {
                listTt.remove(index);
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
            }
        }
    }

    public void update() {
        int index = tableShowData.getSelectedRow();
        ThongTin tt = listTt.get(index);

        try {
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Chọn dòng cần cập nhật");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }

        try {
            if (txtHoTen.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống tên ");
                return;
            } else {
                tt.setHoTen(txtHoTen.getText().trim());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }

        try {
            tt.setGioiTinh(rdoNam.isSelected() ? "Nam" : "Nữ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }

        try {
            if (txtKyNang.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống kỹ năng");
                return;
            } else {
                tt.setKyNang(txtKyNang.getText().trim());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
        try {
            tt.setNganhHoc((String) cbbNganhHoc.getSelectedItem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }

        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
    }

    public void sortByName() {
        Collections.sort(listTt, (a, b) -> a.getHoTen().compareTo(b.getHoTen()));
    }

    public void clear() {
        txtHoTen.setText("");
        txtKyNang.setText("");
        cbbNganhHoc.setSelectedIndex(0);
        rdoNam.setSelected(true);
    }

    public boolean checkTrung(String newName) {
        boolean check = false;
        for (ThongTin x : listTt) {
            if (x.getHoTen().equals(newName)) {
                check = true;
            }
        }
        return check;
    }

    public String gioiTinh() {
        if (rdoNam.isSelected()) {
            return "Nam";
        } else {
            return "Nữ";
        }
    }

    public void showDetail() {
        ThongTin tt = listTt.get(vitri);
        txtHoTen.setText(tt.getHoTen());
        if (tt.getGioiTinh().equals("Nam")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        cbbNganhHoc.setSelectedItem(tt.getNganhHoc());
        txtKyNang.setText(tt.getKyNang());
        lbHIenTai.setText((vitri + 1) + "/" + listTt.size()); //Hiển thị vị trí hiện tại
        tableShowData.setRowSelectionInterval(vitri, vitri); //Table chọn dòng tương ứng

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrHoSoCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrHoSoCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrHoSoCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrHoSoCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrHoSoCaNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnSapXepTheoTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbNganhHoc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHIenTai;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tableShowData;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKyNang;
    // End of variables declaration//GEN-END:variables

}
